box1_x : 3.2
box1_y : 0.0

box2_x : 3.2
box2_y : 0.9

box3_x : 5.25
box3_y : 0.9

box4_x : 5.25
box4_y : -0.9

box5_x : 3.2
box5_y : -0.9

spin_flag : 1

#if_point: 1.position 0.view
#if_safe: 0.view/unsafe 1.safe

if_point: 0
if_safe: 0
point1: 0
point2: 0
point3: 1
point4: 1

target_qr_x : 1.85
target_qr_y : 0.00

target1_x : 1.07
target1_y : -0.63

target2_x : 2.30
target2_y : -1.75

target3_x : 3.30
target3_y : -0.05

target4_x : 1.50
target4_y : 1.80

# tank
target5_x : 4.63
target5_y : -1.00

target6_x : 6.60
target6_y : 2.2

target7_x : 6.60
target7_y : -2.32

# target7_x : 6.40
# target7_y : -2.40

# target8_x : 5.00
# target8_y : 2.1


target8_x : 0
target8_y : 0

park_left_x: -0.08
park_left_y: 1.6
park_right_x: -0.08
park_right_y: -1.6

target_ring_x : 6.05
target_ring_y : 0.5

ring_back_x : 6.05
ring_back_y : -2.4

# fly height
fly_height : 0.6
err_max : 0.15

check_catapult_x : 0.165
check_catapult_y : 0.145
track_distance : 0.2

qr_msg1 : raccoon
qr_msg2 : squirrel
qr_msg3 : right

#ring params
align_threshold : 5
adjust_step : 0.05
backward_step : 0.1
max_backward : 0.5
through_distance : 3.0

sigma_a : 0.1
tank_time : 0
tank_shred : 0

camera_height : 0.062

err_max_ego : 0.25
camera_offset_body_x : 0.085
if_debug : 1
# 1为自动切offboard，0为手动切offboard 