# tent
target1_x : 0.0
target1_y : 3.00

# bridge
target2_x : 1.90
target2_y : 3.30

# pillbox
target3_x : 1.10
target3_y : 1.10

# car
target4_x : 1.60
target4_y : -0.9

# tank
target5_x : 1.10
target5_y : -3.20

# 门口
target6_x : 3.9
target6_y : 3.0

# 降落
target7_x : 3.70
target7_y : -2.90

# 拐角处
target8_x : 2.40
target8_y : 3.00

err_max : 0.15

check_catapult_x : 0.17
check_catapult_y : 0.14
track_distance : 0.2


sigma_a : 0.1
tank_time : 0
tank_shred : 0

camera_height : 0.05

err_max_ego : 0.25

camera_offset_body_x : 0.0
if_debug : 1
# 1为自动切offboard，0为手动切offboard 
door_step : 0
door_shred : 0.5
line_shred : 0.1

door_adjust_range : 80

if_realsence : 0

door_check_num : 5

landing_gear : 0.105