# tent
target1_x : 1.79
target1_y : 2.73

# pillbox
target2_x : 1.95
target2_y : -1.49

# car
target3_x : 3.83
target3_y : -0.2

# tent
target4_x : 3.95
target4_y : 1.80

# tank
target5_x : 1.10
target5_y : -3.20

# 门口
target6_x : 8.18
target6_y : 2.75

# 降落
target7_x : 8.18
target7_y : -3.42

# 拐角处
target8_x : 6.13
target8_y : 2.75

check_door_1_y : 0.8
check_door_2_y : -1.1

err_max : 0.15

# check_catapult_x : 0.125
# check_catapult_y : 0.125
check_catapult_x : 0
check_catapult_y : 0
track_distance : 0.2


sigma_a : 0.1
tank_time : 0
tank_shred : 0

camera_height : 0.04

err_max_ego : 0.25

camera_offset_body_x : 0.08
if_debug : 1
# 1为自动切offboard，0为手动切offboard 
door_step : 0
door_shred : 0.5
line_shred : 0.1

door_adjust_range : 80

if_realsence : 0

door_check_num : 3

landing_gear : 0.0

gravity_offset_x : 0.0

# 投放固定靶子

target_1 : "car"
target_2 : "bridge"
target_3 : "pillbox"  
